name: ML4H 2021
tagline: ML4H Machine Learning for Health
date: December 2021
citation_date: December 2021
proceedings_title: Proceedings of ML4H 2021
analytics: UA-
logo:
  image: static/images/logo.png
  width: auto
  height: 50px
  alt_text: 'ML4H logo'
# uncomment the following line to show the site title next to the logo image
site_title: ML4H 2021
page_title:
  prefix: 'ML4H'
  separator: ': '
background_image: static/images/main_ml4h.jpg
organization: ML4H Organization Committee
registration:
  url: 'register.html'
  link_text: Registration opens February 2021

# Remove or change to your chat server.
chat_server: chat.ml4h.cc
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0: false
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
